# Generated by Django 4.1.7 on 2023-05-08 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('category', models.CharField(choices=[('', 'Choose Category'), ('hats', 'Hats'), ('sweaters', 'Sweaters and Jumpers'), ('scarves', 'Scarves'), ('blankets', 'Blankets and Throws'), ('cardigans', 'Cardigans'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('toys', 'Toys'), ('other', 'Other')], max_length=64)),
                ('description', models.CharField(max_length=6400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('begginer', 'Begginer'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('expert', 'Expert/Grandma')], max_length=64)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
