# Generated by Django 4.1.7 on 2023-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0003_rename_recepie_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('', 'Choose level'), ('begginer', 'Begginer'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('expert', 'Expert/Grandma')], max_length=64),
        ),
    ]
