# Generated by Django 4.1.7 on 2023-05-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0004_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='jarn_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knitout.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'step_num')},
            },
        ),
    ]
