# Generated by Django 4.1.7 on 2023-05-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0005_remove_recipe_description_recipe_jarn_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='step_num',
            new_name='step',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('recipe', 'step')},
        ),
    ]
