# Generated by Django 4.1.7 on 2023-05-11 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0006_rename_step_num_step_step_alter_step_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='user_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
