# Generated by Django 4.1.7 on 2023-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0009_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to='recipes/'),
        ),
    ]
