# Generated by Django 4.1.7 on 2023-05-18 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitout', '0010_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='bookmark_user',
            field=models.ManyToManyField(blank=True, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
